services:
  http-mock:
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION:-22}
        - MOCK_PATH=${MOCK_PATH:-mocks}
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./mocks:/app/mocks
